apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc
  labels:
    app: vpromc
spec:
  selector:
    matchLables:
      app: vpromc
    replicas: 1
    templates:
      metadata:
        labels:
          app: vpromc
      spec:
        contianers:
          - name: vpromc
            image: memcached
            ports:
              - name: vpromc-port
                containerPort: 11211

