apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpro-db-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  hostPath:
    path: /mnt/data  # Adjust this for your setup, e.g., EBS volume path
